apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  application.instanceLabelKey: "app.kubernetes.io/name"
  application.instanceLabelValue: "my-app"
  url: https://argocd-server.argocd.svc.cluster.local
